### ISSUE TITLE
Support other targets

### ISSUE THREAD

**Issue by hfhbd** [cashapp/molecule#112]
I would like to use molecule on other targets as well: native targets, JS(IR) and plain jvm.

Related: https://github.com/JetBrains/androidx/pull/292

**Comment by JakeWharton** [comment]
JS and JVM are already supported per #2.

We are aware of (and advocates for) more targets being supported for use in Redwood. We will update to include them in this library only when they reach stable versions, however. I closed #2 when we landed JS and JVM because I didn't think we need a tracking issue for native. I would prefer to re-open #2 and use it to track the addition of new targets.

**Comment by hfhbd** [comment]
Sorry I don't know why I was unable to find this issue 🤦🏻‍♂️

Any reasons to define only nodeJS? (Although kotlin JS is the same for browser target too)

Okay, so I/we have to wait for Compose 1.2, hopefully with its support.

**Comment by JakeWharton** [comment]
That's just where we run JS tests. It shouldn't affect where you run the actual code.
