### ISSUE TITLE
Kotlin 1.9.23 compatible release

### ISSUE THREAD

**Issue by aftabahmadTW** [cashapp/molecule#411]
Hi team,

Just wanted to know when the 1.9.23 compatible release would be available?

**Comment by JakeWharton** [comment]
I wasn't planning on doing one, because if you specify the compiler version separately you never need to wait for a release to upgrade your Kotlin version: https://github.com/cashapp/molecule?tab=readme-ov-file#custom-compose-compiler.

However, I want to ship the change that disables the klib signature checks, so I'll just do a quick release today.

**Comment by JakeWharton** [comment]
https://github.com/cashapp/molecule/releases/tag/1.4.2
