### ISSUE TITLE
MoleculeTurbine emits duplicate values

### ISSUE THREAD

**Issue by jingibus** [cashapp/molecule#65]
MoleculeTurbine can emit duplicate output values, which results in tests that assert non-stateful behavior.

**Comment by mattprecious** [comment]
Is the situation here that the backing state changes which triggers recomposition, but that state doesn't affect the logic so it re-emits the previous value?

**Comment by jingibus** [comment]
Right: the backing state changes, but the resulting ViewModel is identical.

**Comment by mattprecious** [comment]
I think I need an example of when this is undesirable and what API/behavior changes you'd like to see?

`MoleculeTurbine` will only attempt to recompose if you await an event, so it will only emit the duplicate value if you ask it to. If the goal is to not have to assert against state changes that don't affect the value, then you can remove the await.

If we de-dupe the value behind the scenes, then you lose the ability to assert because the only way to assert a lack of value is to await the timeout. Then your tests will be slow. We could add an `awaitUnchanged()`, but if that's what you're after then with the current APIs you can hold onto the previous value and compare it to the next one from `awaitItem()`.

**Comment by jingibus** [comment]
> `MoleculeTurbine` will only attempt to recompose if you await an event, so it will only emit the duplicate value if you ask it to. If the goal is to not have to assert against state changes that don't affect the value, then you can remove the await.

The big question for me is — what am I `await`ing on? Am I awaiting on a `StateFlow`? As a consumer of the API, that's what I expect: Molecule is a way of defining a `StateFlow`. 

Or am I triggering a recomposition? If that's the case, then I should *always* get a fresh value, regardless of whether the internal state has been updated or not.  

The current state of affairs is that I get a new output every time the internal state changes. This might make sense when writing validations for Molecule itself, because those internal details are important to validate, but as a consumer of Molecule it leads to engineers writing meaningless validations: "This test failed because it emitted 5 `LoanViewModel(loanAmount = 1)`s instead of 4." That won't make a difference in prod, so I don't understand why it should be in the test. 

It might even lead engineers to believe that Molecule behaves the way the tests behave. Which is concerning, because.... well, it *should* behave the way the tests behave, right?

> If we de-dupe the value behind the scenes, then you lose the ability to assert because the only way to assert a lack of value is to await the timeout.

My perspective is that this is a fact of life in testing: you can't assert on things that aren't visible. If you want to assert on them.. make them visible.

**Comment by mattprecious** [comment]
> If that's the case, then I should always get a fresh value, regardless of whether the internal state has been updated or not.

Not sure if this is possible! I'll have to take a closer look at the APIs. We're currently at the whim of Compose for how it determines that recomposition is needed.

> The current state of affairs is that I get a new output every time the internal state changes. [...] "This test failed because it emitted 5 LoanViewModel(loanAmount = 5)s instead of 4."

This isn't entirely true, though. You can change as much state as you want between awaits and you'll only get one value out when you `awaitItem()`.

```kotlin
val events = MutableSharedFlow<Unit>()

testMolecule({
  var count by remember { mutableStateOf(0) }

  LaunchedEffect(Unit) {
    events.collect {
      count++
    }
  }

  count
}) {
  assertEquals(0, awaitItem())

  events.emit(Unit)
  events.emit(Unit)
  events.emit(Unit)
  events.emit(Unit)
  events.emit(Unit)

  assertEquals(5, awaitItem())

  assertFailsWith<TimeoutCancellationException> { awaitItem() }
}
```

However, yes, if you choose you can also write overly verbose tests:

```kotlin
  assertEquals(0, awaitItem())

  events.emit(Unit)
  assertEquals(1, awaitItem())

  events.emit(Unit)
  assertEquals(2, awaitItem())

  events.emit(Unit)
  assertEquals(3, awaitItem())

  events.emit(Unit)
  assertEquals(4, awaitItem())

  events.emit(Unit)
  assertEquals(5, awaitItem())
```

So the granularity at which `MoleculeTurbine` emits items is entirely up to the test writer. 

> It might even lead engineers to believe that Molecule behaves the way the tests behave. Which is concerning, because.... well, it should behave the way the tests behave, right?

The thing about this is that we can't reliably match production because production behavior is entirely dependent on the frame clock and the timing at which state gets updated. If two states are being updated from two different coroutines, then in production, a particular recomposition could either see one or both of the updates depending on where the frame sync landed. If we try to match production for testing, then that will likely lead to flaky tests.

**Comment by jingibus** [comment]
> So the granularity at which MoleculeTurbine emits items is entirely up to the test writer.

My example was wrong. But even then — why should the test author care about whether the internal state was updated or not? This does not match the `StateFlow` API, which implicitly deduplicates.

> The thing about this is that we can't reliably match production because production behavior is entirely dependent on the frame clock and the timing at which state gets updated. If two states are being updated from two different coroutines, then in production, a particular recomposition could either see one or both of the updates depending on where the frame sync landed. If we try to match production for testing, then that will likely lead to flaky tests.

But from the perspective of production code, the value is a state consumed in a pull fashion, right? (I'm really winging it, so... I'm sure I'm whiffing the implementation details a second time.) It can receive the same value 5 times in 25ms, and it means the same as if it had received the value one time. They're states, and so the meaning of the flow is in the distinct values in the stream. If a production implementation were to behave differently upon receiving 2 events versus receiving 1 event, it would be an error.

There's another point above I want to revisit:

> If we de-dupe the value behind the scenes, then you lose the ability to assert because the only way to assert a lack of value is to await the timeout.

The benefit of this is narrow. The code under test will only emit a new value if the interaction under test triggers a write to the composed state. This often won't happen: a lot of event handling code doesn't touch state, for example, and the TDD flow of "let's write a failing test" never will. So this ends up adding another ineffective half measure to the pile of incomplete coroutines testing solutions.

**Comment by JakeWharton** [comment]
> Molecule is a way of defining a `StateFlow`.

Molecule **has** a way of defining a `StateFlow`. It also has a way of defining a `Flow` and we'll probably expose `State` at some point. We also originally had modules for defining `Observable`.

**Comment by jingibus** [comment]
> Molecule has a way of defining a StateFlow. It also has a way of defining a Flow and we'll probably expose State at some point. We also originally had modules for defining Observable.

That is really really awesome. I hate testing `StateFlow`, but I usually want `StateFlow` in prod.

The `StateFlow` is just a transformation on what a molecule implementation produces, though. That's at the heart of my issue here: Is the sequence of values produced by a molecule implementation stateful? Or is it eventful? Because if it's stateful (which I assume that it is), the current behavior doesn't appear to make much sense to me, and I'd find it confusing to write tests against.

**Comment by jingibus** [comment]
No longer relevant
